server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: producer_route
          uri: http://localhost:8082
          predicates:
            - Path=/producer/**


logging:
  file:
    name: logs/spring-boot-logger.log
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
